//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::client_credentials::Entity as ClientCredentials;
pub use super::movies::Entity as Movies;
pub use super::pods::Entity as Pods;
pub use super::users::Entity as Users;
