mod add;
mod auto_destruct;
pub mod chunking;
pub mod cli;
pub mod cloudflared_downloader;
pub mod cloudflared_manager;
pub mod core;
pub mod cubby_api_client;
pub mod filtering;
pub mod mcp;
pub mod onboarding;
pub mod permission_checker;
pub mod pipe_manager;
mod resource_monitor;
mod server;
pub mod service_manager;
pub mod setup_state;
pub mod text_embeds;
mod video;
pub mod video_cache;
pub mod video_utils;
pub use add::handle_index_command;
pub use auto_destruct::watch_pid;
pub use axum::Json as JsonResponse;
pub use cli::Cli;
pub use cloudflared_downloader::ensure_cloudflared;
pub use cloudflared_manager::CloudflaredManager;
pub use core::start_continuous_recording;
pub use cubby_api_client::CubbyApiClient;
pub use cubby_core::Language;
pub use onboarding::run_onboarding_flow;
pub use pipe_manager::PipeManager;
pub use resource_monitor::{ResourceMonitor, RestartSignal};
pub use server::health_check;
pub use server::AppState;
pub use server::ContentItem;
pub use server::HealthCheckResponse;
pub use server::PaginatedResponse;
pub use server::SCServer;
pub use server::{api_list_monitors, MonitorInfo};
pub use video::VideoCapture;
pub mod embedding;
