// Generated by Wrangler by running `wrangler types`

interface Env {
	STYTCH_CLIENT_ID: string;
	STYTCH_AUTH_URL: string;
	STYTCH_TOKEN_URL: string;
	STYTCH_ISSUER: string;
	REDIRECT_URI: string;
	REQUESTED_SCOPES: string;
	CUBBY_API_URL: string;
	SESSION_SECRET: string;
	SECURE_COOKIES: string;
}
