#:schema node_modules/wrangler/config-schema.json
name = "cubby-frontend"
main = "src/index.tsx"
compatibility_date = "2025-09-24"
workers_dev = false
preview_urls = false
keep_vars = true

[[routes]]
pattern = "app.cubby.sh"
custom_domain = true

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "public"




