#:schema node_modules/wrangler/config-schema.json
name = "cubby-api"
main = "src/index.ts"
compatibility_date = "2025-09-24"
workers_dev = false
preview_urls = false
keep_vars = true

[[routes]]
pattern = "api.cubby.sh"
custom_domain = true

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "public"

[dev]
port=8787




